version: "3.8"

services:
  # Database
  postgres:
    image: postgres:14
    container_name: food-delivery-postgres
    restart: always
    ports:
      - "5434:5432"  # Changed port to avoid conflict
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=food_delivery
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Only mount init script if it exists
      # - ../docker/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  # Cache
  redis:
    image: redis:alpine
    container_name: food-delivery-redis
    restart: always
    ports:
      - "6381:6379"  # Changed port to avoid conflict
    volumes:
      - redis-data:/data

  # Additional services for development
  mailhog:
    image: mailhog/mailhog
    container_name: food-delivery-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
      
  # Database Management System
  pgadmin:
    image: dpage/pgadmin4
    container_name: food-delivery-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fooddelivery.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
