FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install dependencies inside the container
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
