services:
  - type: web
    name: food-delivery-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile.prod # This will use your production Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: food-delivery-db
    region: frankfurt
    plan: free
    ipAllowList: []
